src/Entity/Rate.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RateRepository")
 */
class Rate
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $from_hours;

    /**
     * @ORM\Column(type="integer")
     */
    private $to_hours;

    /**
     * @ORM\Column(type="boolean")
     */
    private $weekday = false;

    /**
     * @ORM\Column(type="float")
     */
    private $rate;

    public function __construct()
    {
        $this->weekday = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFromHours(): ?int
    {
        return $this->from_hours;
    }

    public function setFromHours(int $from_hours): self
    {
        $this->from_hours = $from_hours;

        return $this;
    }

    public function getToHours(): ?int
    {
        return $this->to_hours;
    }

    public function setToHours(int $to_hours): self
    {
        $this->to_hours = $to_hours;

        return $this;
    }

    public function getWeekday(): ?string
    {
        return (bool)$this->weekday;
    }

    public function setWeekday(string $weekday): self
    {
        $this->weekday = (bool)$weekday;

        return $this;
    }

    public function getRate(): ?float
    {
        return $this->rate;
    }

    public function setRate(float $rate): self
    {
        $this->rate = $rate;

        return $this;
    }
}

src/Form/RateType.php
<?php

namespace App\Form;

use App\Entity\Rate;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Doctrine\DBAL\Types\TextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\PositiveOrZero;
use Symfony\Component\Validator\Constraints\Range;

class RateType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('from_hours', NumberType::class, ['constraints' => [
                new NotBlank(),
                new PositiveOrZero(),
                new Range(['min' => 0, 'max' => 12])
            ]])
            ->add('to_hours',NumberType::class, ['constraints' => [
                new NotBlank(),
                new PositiveOrZero(),
                new Range(['min' => 0, 'max' => 12])
            ]])
            ->add('rate', NumberType::class, ['constraints' => [
                new NotBlank(),
                new PositiveOrZero()
            ]])
            ->add('weekday', CheckboxType::class, [
                'required' => false
            ])
        ;

        $builder->get('weekday')
                ->addModelTransformer(new CallbackTransformer(function($weekdayIntToBoolean) {
                    return (bool)$weekdayIntToBoolean;
                }, function($weekdayBooleanToInt) {
                    return (int)$weekdayBooleanToInt;
                }));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Rate::class,
        ]);
    }
}

src/Controller/RateController.php
<?php

namespace App\Controller;

use App\Entity\Rate;
use App\Form\RateType;
use App\Repository\RateRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/rate")
 */
class RateController extends AbstractController
{
    /**
     * @Route("/", name="rate_index", methods={"GET"})
     */
    public function index(RateRepository $rateRepository): Response
    {
        return $this->render('rate/index.html.twig', [
            'rates' => $rateRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="rate_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $rate = new Rate();
        $form = $this->createForm(RateType::class, $rate);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($rate);
            $entityManager->flush();

            return $this->redirectToRoute('rate_index');
        }

        return $this->render('rate/new.html.twig', [
            'rate' => $rate,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="rate_show", methods={"GET"})
     */
    public function show(Rate $rate): Response
    {
        return $this->render('rate/show.html.twig', [
            'rate' => $rate,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="rate_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Rate $rate): Response
    {

        $form = $this->createForm(RateType::class, $rate);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('rate_index');
        }

        return $this->render('rate/edit.html.twig', [
            'rate' => $rate,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="rate_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Rate $rate): Response
    {
        if ($this->isCsrfTokenValid('delete'.$rate->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($rate);
            $entityManager->flush();
        }

        return $this->redirectToRoute('rate_index');
    }
}

templates/rate/_delete_form.html.twig
<form method="post" action="{{ path('rate_delete', {'id': rate.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ rate.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/rate/_form.html.twig
{{ form_start(form) }}
    <div class="form-group">
        {{  form_label(form.from_hours) }}
        {{  form_widget(form.from_hours, { attr: {'class': 'form-control'} }) }}
    </div>
    <div class="form-group">
        {{  form_label(form.to_hours) }}
        {{  form_widget(form.to_hours, { attr: {'class': 'form-control'} }) }}
    </div>
    <div class="form-group">
        {{  form_label(form.rate) }}
        {{  form_widget(form.rate, { attr: {'class': 'form-control'} }) }}
    </div>
    <div class="form-check">
        {{  form_widget(form.weekday, { attr: {'class': 'form-check-input'} }) }}
        {{  form_label(form.weekday) }}
    </div>

    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/rate/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Rate{% endblock %}

{% block body %}
    <h1>Edit Rate</h1>

    {{ include('rate/_form.html.twig', {'button_label': 'Update'}) }}
    <br>
    <a href="{{ path('rate_index') }}">back to list</a>
    <br> <br>
    {{ include('rate/_delete_form.html.twig') }}
{% endblock %}

templates/rate/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Rate index{% endblock %}

{% block body %}
    <h1>Rate list</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>From hour</th>
                <th>To hour</th>
                <th>Rate</th>
                <th>Weekday</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for rate in rates %}
            <tr>
                <td>{{ rate.id }}</td>
                <td>{{ rate.fromHours }}</td>
                <td>{{ rate.toHours }}</td>
                <td>{{ rate.rate }}</td>
                <td>{{ rate.weekday ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('rate_edit', {'id': rate.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('rate_new') }}">Create new</a>
{% endblock %}

templates/rate/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Rate{% endblock %}

{% block body %}
    <h1>Create new Rate</h1>

    {{ include('rate/_form.html.twig') }}

    <a href="{{ path('rate_index') }}">back to list</a>
{% endblock %}

templates/rate/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Rate{% endblock %}

{% block body %}
    <h1>Rate</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ rate.id }}</td>
            </tr>
            <tr>
                <th>From_hours</th>
                <td>{{ rate.fromHours }}</td>
            </tr>
            <tr>
                <th>To_hours</th>
                <td>{{ rate.toHours }}</td>
            </tr>
            <tr>
                <th>Weekday</th>
                <td>{{ rate.weekday ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('rate_index') }}">back to list</a>

    <a href="{{ path('rate_edit', {'id': rate.id}) }}">edit</a>

    {{ include('rate/_delete_form.html.twig') }}
{% endblock %}