src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="An user with this email address already exists")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    private $plainPassword;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\WorkingTime", mappedBy="user", orphanRemoval=true)
     */
    private $workingTimes;

    public function __construct()
    {
        $this->workingTimes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        $this->plainPassword = null;
    }

    public function getPlainPassword() {
        return $this->plainPassword;
    }

    /**
     * @return Collection|WorkingTime[]
     */
    public function getWorkingTimes(): Collection
    {
        return $this->workingTimes;
    }

    public function addWorkingTime(WorkingTime $workingTime): self
    {
        if (!$this->workingTimes->contains($workingTime)) {
            $this->workingTimes[] = $workingTime;
            $workingTime->setUser($this);
        }

        return $this;
    }

    public function removeWorkingTime(WorkingTime $workingTime): self
    {
        if ($this->workingTimes->contains($workingTime)) {
            $this->workingTimes->removeElement($workingTime);
            // set the owning side to null (unless already changed)
            if ($workingTime->getUser() === $this) {
                $workingTime->setUser(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->email;
    }

    public function hasRole($searchRole) {
        foreach($this->roles as $role) {
            if(strpos($role, $searchRole) !== false) {
                return true;
            }
        }

        return false;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ asset('assets/css/main.css') }}">
    {% block stylesheets %}{% endblock %}
</head>
<body>
<div class="container">

    <header>
        <div class="logo float-left"><h1><a href="{{ path('home') }}">Time Tracker</a></h1></div>
        <div class="login float-right">
            {% if not app.user %}
                <a href="{{ path('app_login') }}">Login</a>
            {%  else  %}Hello {{ app.user.username }} |
                {% if is_granted('ROLE_ADMIN') %}<a href="{{ path('user_index') }}">Create Employee record</a> |{% endif %}
                {% if is_granted('ROLE_ADMIN') %}<a href="{{ path('rate_index') }}">Create rate</a> |{% endif %}
                {% if is_granted('ROLE_ADMIN') %}<a href="{{ path('working_time_index') }}">View working time</a> |{% endif %}
                {% if is_granted('ROLE_USER') and not is_granted('ROLE_ADMIN') %}<a href="{{ path('working_time_index') }}">Log working time</a> |{%  endif %}
                <a href="{{  path('app_logout') }}">Logout</a>
            {%  endif %}
        </div>
    </header>
    <div class="row">
        <div class="col-md-12 inner-content">
            {% block body %}{% endblock %}
        </div>
    </div>
    <footer>Time Tracker Task 2020</footer>
</div>

{% block javascripts %}{% endblock %}
</body>
</html>