src/Entity/WorkingTime.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\WorkingTimeRepository")
 */
class WorkingTime
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $day_at;

    /**
     * @ORM\Column(type="integer")
     */
    private $hours;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="workingTimes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="float")
     */
    private $wagePerDay;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDayAt(): ?\DateTimeInterface
    {
        return $this->day_at;
    }

    public function setDayAt(\DateTimeInterface $day_at): self
    {
        $this->day_at = $day_at;

        return $this;
    }

    public function getHours(): ?int
    {
        return $this->hours;
    }

    public function setHours(int $hours): self
    {
        $this->hours = $hours;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getWagePerDay(): ?float
    {
        return $this->wagePerDay;
    }

    public function setWagePerDay(float $wagePerDay): self
    {
        $this->wagePerDay = $wagePerDay;

        return $this;
    }
}

src/Form/WorkingTimeType.php
<?php

namespace App\Form;

use App\Entity\WorkingTime;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class WorkingTimeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('day_at', DateTimeType::class, ['date_widget' => 'single_text'])
            ->add('hours')

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => WorkingTime::class,
        ]);
    }
}

src/Controller/WorkingTimeController.php
<?php

namespace App\Controller;

use App\Entity\WorkingTime;
use App\Form\WorkingTimeType;
use App\Repository\WorkingTimeRepository;
use App\Service\CalculateWage;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/working/time")
 */
class WorkingTimeController extends AbstractController
{
    /**
     * @Route("/", name="working_time_index", methods={"GET"})
     */
    public function index(WorkingTimeRepository $workingTimeRepository): Response
    {
        return $this->render('working_time/index.html.twig', [

            'working_times' =>
                !$this->getUser()->hasRole('ROLE_ADMIN') ?
                    $workingTimeRepository->findBy(['user' => $this->getUser()]) :
                    $workingTimeRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="working_time_new", methods={"GET","POST"})
     */
    public function new(Request $request, CalculateWage $calculateWage): Response
    {
        $workingTime = new WorkingTime();
        $form = $this->createForm(WorkingTimeType::class, $workingTime);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $workingTime->setUser($this->getUser());
            $workingTime->setWagePerDay($calculateWage->calculate($workingTime->getDayAt(), $workingTime->getHours()));
            $entityManager->persist($workingTime);
            $entityManager->flush();

            return $this->redirectToRoute('working_time_index');
        }

        return $this->render('working_time/new.html.twig', [
            'working_time' => $workingTime,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="working_time_show", methods={"GET"})
     */
    public function show(WorkingTime $workingTime): Response
    {
        return $this->render('working_time/show.html.twig', [
            'working_time' => $workingTime,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="working_time_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, WorkingTime $workingTime, CalculateWage $calculateWage): Response
    {
        $form = $this->createForm(WorkingTimeType::class, $workingTime);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager = $this->getDoctrine()->getManager();
            $workingTime->setWagePerDay($calculateWage->calculate($workingTime->getDayAt(), $workingTime->getHours()));

            $entityManager->persist($workingTime);
            $entityManager->flush();

            return $this->redirectToRoute('working_time_index');
        }

        return $this->render('working_time/edit.html.twig', [
            'working_time' => $workingTime,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="working_time_delete", methods={"DELETE"})
     */
    public function delete(Request $request, WorkingTime $workingTime): Response
    {
        if ($this->isCsrfTokenValid('delete'.$workingTime->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($workingTime);
            $entityManager->flush();
        }

        return $this->redirectToRoute('working_time_index');
    }
}

templates/working_time/_delete_form.html.twig
<form method="post" action="{{ path('working_time_delete', {'id': working_time.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ working_time.id) }}">
    <button class="btn">Delete</button>
</form>

templates/working_time/_form.html.twig
{{ form_start(form) }}
<div class="form-group">
    {{ form_label(form.day_at) }}
    {{ form_widget(form.day_at, {attr: { 'class': 'form-control' } }) }}
</div>
<div class="form-group">
    {{ form_label(form.hours) }}
    {{ form_widget(form.hours, {attr: { 'class': 'form-control' } }) }}
</div>

<button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/working_time/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit WorkingTime{% endblock %}

{% block body %}
    <h1>Edit WorkingTime</h1>

    {{ include('working_time/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('working_time_index') }}">back to list</a>

    {{ include('working_time/_delete_form.html.twig') }}
{% endblock %}

templates/working_time/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}WorkingTime index{% endblock %}

{% block body %}
    <h1>WorkingTime index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Day_at</th>
                <th>Hours</th>
                {%  if is_granted('ROLE_ADMIN') %}
                <th>User</th>
                {% endif %}
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for working_time in working_times %}
            <tr>
                <td>{{ working_time.id }}</td>
                <td>{{ working_time.dayAt ? working_time.dayAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ working_time.hours }}</td>
                {%  if is_granted('ROLE_ADMIN') %}
                    <td>{{ working_time.user }}</td>
                {% endif %}
                <td>
                    <a href="{{ path('working_time_show', {'id': working_time.id}) }}">show</a>
                    <a href="{{ path('working_time_edit', {'id': working_time.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('working_time_new') }}">Create new</a>
{% endblock %}

templates/working_time/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New WorkingTime{% endblock %}

{% block body %}
    <h1>Log new working time</h1>

    {{ include('working_time/_form.html.twig') }}

    <a href="{{ path('working_time_index') }}">back to list</a>
{% endblock %}

templates/working_time/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}WorkingTime{% endblock %}

{% block body %}
    <h1>WorkingTime</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ working_time.id }}</td>
            </tr>
            <tr>
                <th>Day_at</th>
                <td>{{ working_time.dayAt ? working_time.dayAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Hours</th>
                <td>{{ working_time.hours }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('working_time_index') }}">back to list</a>

    <a href="{{ path('working_time_edit', {'id': working_time.id}) }}">edit</a>

    {{ include('working_time/_delete_form.html.twig') }}
{% endblock %}